-- Migration for Multi-Price Architecture
ALTER TABLE URUN ADD COLUMN FIYAT_MAGAZA DECIMAL(14,4) NULL DEFAULT 0.0000 AFTER ACIKLAMA;
ALTER TABLE URUN ADD COLUMN FIYAT_TELEFON DECIMAL(14,4) NULL DEFAULT 0.0000 AFTER FIYAT_MAGAZA;
ALTER TABLE URUN ADD COLUMN FIYAT_DIS_PLATFORM DECIMAL(14,4) NULL DEFAULT 0.0000 AFTER FIYAT_TELEFON;

-- Migrate existing single price FIYAT into FIYAT_MAGAZA
UPDATE URUN SET FIYAT_MAGAZA = FIYAT WHERE (FIYAT_MAGAZA IS NULL OR FIYAT_MAGAZA = 0) AND FIYAT > 0;
